############ First Version ############ 

using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using System;

namespace Parcels
{
    public class ParcelCounter
    {
        public ParcelCounter()
        {
        }
        public int Count()
        {
            var count = 0;

            var options = new PromptSelectionOptions();
            options.MessageForAdding = "Add parcels";
            options.MessageForRemoval = "Remove parcels";

            var filter = new SelectionFilter(new TypedValue[]
            {
                new TypedValue((int)DxfCode.Start, "LWPOLYLINE"),
                new TypedValue((int)DxfCode.LayerName, "Parcels"),
            });
            var result = Active.Editor.GetSelection(options, filter);
            if(result.Status == PromptStatus.OK)
            {
                Active.UsingTransaction(tr =>
                {
                    foreach (var objectId in result.Value.GetObjectIds())
                    {
                        var polyline = (Polyline)tr.GetObject(objectId, OpenMode.ForRead);
                        if (polyline.Closed)
                        {
                            count++;
                        }
                    }
                });
            }
            return count;
        }
    }
}

############ Last Version ############ 

        public ParcelSummary Count()
        {
            var summary = new ParcelSummary();

            var result = SelectParcels();

            if(result.Status == PromptStatus.OK)
            {
                Active.UsingTransaction(tr =>
                {
                    foreach (var objectId in result.Value.GetObjectIds())
                    {
                        var polyline = (Polyline)tr.GetObject(objectId, OpenMode.ForRead);
                        if (polyline.Closed)
                        {
                            summary.Count++;
                            summary.Area += polyline.Area;
                        }
                    }
                });
            }
            return summary;
        }

        private PromptSelectionResult SelectParcels()
        {
            var options = new PromptSelectionOptions();
            options.MessageForAdding = "Add parcels";
            options.MessageForRemoval = "Remove parcels";

            var filter = new SelectionFilter(new TypedValue[]
            {
                new TypedValue((int)DxfCode.Start, "LWPOLYLINE"),
                new TypedValue((int)DxfCode.LayerName, "Parcels"),
            });
            return Active.Editor.GetSelection(options, filter);
        }