############ First Version ############ 

using Autodesk.AutoCAD.ApplicationServices.Core;
using Autodesk.AutoCAD.Colors;
using Autodesk.AutoCAD.DatabaseServices;
using System;
using System.Drawing;

namespace Parcels
{
    public class ParcelLayer
    {
        public ParcelLayer()
        {
        }
        public void Create()
        {
            var layerName = "Parcels";
            var document = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;
            var database = document.Database;

            using(var transaction = database.TransactionManager.StartTransaction())
            {
                var layerTable = (LayerTable)transaction.GetObject(database.LayerTableId, OpenMode.ForRead);
                LayerTableRecord layer;
                if (layerTable.Has(layerName) == false)
                {
                    layer = new LayerTableRecord
                    {
                        Name = layerName,
                        Color = Color.FromColorIndex(ColorMethod.ByAci, 161)
                    };

                    layerTable.UpgradeOpen();
                    layerTable.Add(layer);
                    transaction.AddNewlyCreatedDBObject(layer, true);
                }

                database.Clayer = layerTable[layerName];

                transaction.Commit();
            };
        }
    }
}

############ Second Version ############

        public void Create()
        {
            var layerName = "Parcels";

            Active.UsingTransaction(transaction => 
            {
                var database = Active.Database;
                var layerTable = (LayerTable)transaction.GetObject(database.LayerTableId, OpenMode.ForRead);
                LayerTableRecord layer;
                if (layerTable.Has(layerName) == false)
                {
                    layer = new LayerTableRecord
                    {
                        Name = layerName,
                        Color = Color.FromColorIndex(ColorMethod.ByAci, 161)
                    };

                    layerTable.UpgradeOpen();
                    layerTable.Add(layer);
                    transaction.AddNewlyCreatedDBObject(layer, true);
                }

                database.Clayer = layerTable[layerName];

                transaction.Commit();
            });
        }
